---
title: "S-gene positive pillar 2 cases VOC Supplementary"
author: "Rob Challen"
date: '`r format(Sys.Date(), "%d-%m-%Y")`'
output: 
  pdf_document:
    fig_caption: yes
header-includes:
  \usepackage{float}
  \floatplacement{figure}{H}
knit: (function(inputFile, encoding,...) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = here::here("output/"))})
fig_width: 7
fig_height: 5
out.width: "100%"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)

here::i_am("s-pos-supp-2.Rmd")
source(here::here("common-setup.R"))
source(here::here("s-pos-clusters.R"))
source(here::here("s-pos-data.R"))

```

## Modelled growth rate

```{r}

lsoaCentroid = dpc$geog$getMap("LSOA11")
lsoaCentroid = lsoaCentroid %>% sf::st_centroid()

mapping = dpc$geog$getContainedIn(inputSf = lsoaCentroid,outputShape = aocMap,outputIdVar = areaName)
mapping %>% readr::write_csv(here::here("input/LSOAtoAOCMapping.csv"))

# mapping = readr::read_csv(here::here("input/LSOAtoAOCMapping.csv"))
modelled = readr::read_csv(here::here("input/ByLSOAVariantRates-2021-06-02.csv"))

modelledAoc = bind_rows(
  modelled %>% inner_join(mapping, by=c("LSOA_code"="from")) %>% group_by(area = to, week, type) %>% summarise(variantGR = sum(VariantRate)),
  modelled %>% filter(LSOA_code %>% stringr::str_starts("E")) %>% group_by(week, type) %>% summarise(variantGR = sum(VariantRate,na.rm = TRUE)) %>% mutate(area="England")
)

estGR = modelledAoc %>% group_by(area,type) %>% arrange(week) %>%
  mutate(
    gr = (log(variantGR)-log(lag(variantGR)))/7,
    date = week+as.numeric(week-lag(week))/2
  )

#ggplot(estGR,aes(x=date,y=gr,colour=type))+ geom_point()+facet_wrap(vars(area))
doModelBar = function(clustName = paste(names,collapse = "-"), names = clusters[[clustName]]) {
  ggplot(data=estGR %>% filter(area %in% names) %>% rename(name=area),mapping=aes(x=date,y=gr,fill=type))+
    geom_bar(stat="identity",position = "dodge", width=5, colour="black",size=0.1)+
    scale_y_continuous(limits = c(-0.25,0.25))+
    scale_fill_brewer(palette="Set2",name=NULL)+
    scale_x_date(breaks=seq(as.Date("2021-02-04"),Sys.Date(),by = 7),date_labels="%d-%m")+
    ylab("growth rate, r")
}

p1 = doModelBar(names = "England")+
  facet_wrap(vars(name),nrow=1)+
  theme(axis.text.x = element_text(angle=0,hjust=0.5))+
  guides(linetype=guide_none(),colour=guide_none(),fill=guide_none())+
  theme(axis.title.x = element_blank())+
  theme(plot.margin = margin(0, 0, 0, 0, "mm"))

p2 = doModelBar(clustName = "NHS Regions")+
  facet_wrap(vars(name),nrow=1)+
  guides(linetype=guide_none(),colour=guide_none(),fill=guide_none())+
  standardPrintOutput::hideX()+
  theme(plot.margin = margin(0, 0, 0, 0, "mm")) #,axis.ticks.x = element_blank())

p3 = doModelBar(names = c("Bolton","M65 Corridor","Manchester"))+
  facet_wrap(vars(name),nrow=1)+
  guides(linetype=guide_none(),colour=guide_none(),fill=guide_none())+
  standardPrintOutput::hideX()+
  theme(plot.margin = margin(0, 0, 0, 0, "mm")) #,axis.ticks.x = element_blank())

p4 = doModelBar(names = c("Leicester","Nottingham","Birmingham"))+
  facet_wrap(vars(name),nrow=1)+
  standardPrintOutput::smallLegend(spaceLegend = 1)+theme(
    legend.position = "bottom",
    legend.direction = "horizontal"
  )

p5 = (p1/p2/p3/p4 + patchwork::plot_annotation(tag_levels="A"))+patchwork::plot_layout(heights = c(2,2,1.5,1.5))
standardPrintOutput::saveTwoThirdPageFigure(p5,paste0(here::here("output/ModelledGrowth-"),Sys.Date()))

```

```{r}
## Modelled estaimtes

# lsoaCentroid = dpc$geog$getMap("LSOA11")
# lsoaCentroid = lsoaCentroid %>% sf::st_centroid()
# mapping = dpc$geog$getContainedIn(inputSf = lsoaCentroid,outputShape = aocMap,outputIdVar = areaName)
# 
# mapping %>% readr::write_csv(here::here("output/LSOA2AOC.csv"))
# 
# mapping = readr::read_csv(here::here("output/LSOA2AOC.csv"))
# modelled = readr::read_csv(here::here("output/Inputs/ByLSOAVariantRateswDGP.csv/ByLSOAVariantRateswDGP.csv"))
# modelledAoc = modelled %>% inner_join(mapping, by=c("LSOA_code"="from")) %>% group_by(area = to, week, type) %>% summarise(variantGR = sum(VariantRate))
# estGR = modelledAoc %>% group_by(area,type) %>% arrange(week) %>% mutate(diffGR = (log(variantGR)-log(lag(variantGR)))/7, date = week+as.numeric(week-lag(week))/2) 
# ggplot(estGR,aes(x=date,y=diffGR,colour=type))+ geom_point()+facet_wrap(vars(area))
# 
# modelledEng = modelled %>% filter(LSOA_code %>% stringr::str_starts("E")) %>% group_by(week, type) %>% summarise(variantGR = sum(VariantRate,na.rm = TRUE)) %>% mutate(area="England")
# 
# 
# modelledAll = bind_rows(modelledEng,modelledAoc) %>% group_by(area,type) %>%
#   group_modify(function(d,g,...) {
#     tmp_intercept_model = locfit::locfit(variantGR ~ locfit::lp(week, deg=1,nn = 1), d)#, family="qgamma")
#     tmp_slope_model = locfit::locfit(variantGR ~ locfit::lp(week, deg=1,nn = 1), d, deriv=1)
#     dates = min(d$week):max(d$week)
#     rate = predict(tmp_intercept_model, dates, band="local")
#     growth = predict(tmp_slope_model, dates, band="local")
#     return(tibble(date=dates,rate=rate$fit,growth=growth$fit))
#   })
# 
# modelledAll = bind_rows(modelledEng,modelledAoc) %>% group_by(area,type) %>%
#   arrange(week) %>%
# 
# ggplot(modelledEng,aes(x=week,y=variantGR/7,colour=type))+geom_line()+facet_wrap(vars(area),scales = "free")+scale_y_continuous(trans="log1p")
# 
# ggplot(modelledAoc,aes(x=week,y=variantGR,colour=type))+geom_line()+facet_wrap(vars(area),scales = "free")
# 
# ggplot(modelledAll,aes(x=date,y=growth,colour=type))+geom_line()+facet_wrap(vars(area),scales = "free")

modelled2 = readRDS(here::here("input/DataForRob1.RDS"))
modelledMean = modelled2 %>% group_by(date,Modelled_Type) %>% summarise(expected = sum(n)/100) %>% ungroup() %>% tidyr::complete(date,Modelled_Type,fill=list(expected=0))

modelledIncid = modelledMean %>% mutate(
  source = "INLA model",
  type = "incidence",
  statistic = "case",
  ageCat = NA,
  gender=NA,
  subgroup = Modelled_Type,
  code = "E92000001",
  name = "England",
  codeType = "CTRY",
  value = expected,
  Implicit = FALSE
)

modelledGR = modelledIncid %>% filter(date < max(date)-4) %>% tsp$estimateGrowthRate(window = 28)

tmpP = tsp$plotGrowthRate(
  modelledGR,
  colour = subgroup,
                   rlim=c(-0.2,0.2),
                   growthVar = Growth.windowed.value,
                   growthSEVar = Growth.windowed.SE.value,
  ribbons = FALSE
)+facet_wrap(vars(name))+standardPrintOutput::watermark(lab="provisional")+ylab("r - sliding 4 week window")

tmpP %>% saveHalfPageFigure(here::here("output/SpatioTemporalModelledGREngland"))
```

# Additional figures


## Cross validation counts with CLIMB

```{r}
climb = dpc$datasets$getCLIMB()
climb = climb %>% mutate(voc = case_when(
  lineage %>% stringr::str_starts("B.1.1.7") ~ "B.1.1.7",
  lineage %>% stringr::str_starts("B.1.351") ~ "B.1.351",
  lineage %>% stringr::str_starts("P.1") ~ "P.1 & P.2",
  lineage %>% stringr::str_starts("P.2") ~ "P.1 & P.2",
  lineage %>% stringr::str_starts("B.1.617.1") ~ "B.1.617.1",
  lineage %>% stringr::str_starts("B.1.617.2") ~ "B.1.617.2",
  lineage %>% stringr::str_starts("B.1.525") ~ "B.1.525",
  lineage %>% stringr::str_starts("B.1.1.318") ~ "B.1.1.318",
  TRUE ~ "other"
))

tmp1 = climb %>% filter(adm1=="UK-ENG" & sample_date > (combinedSpositives$earliest_specimen_date %>% min(na.rm=TRUE))) %>% group_by(type = voc) %>% summarise(`climb latest` = max(sample_date,na.rm = TRUE),`climb sequences` = n())
tmp2 = combinedSpositives %>% 
  # mutate(type=case_when(
  #   type %>% stringr::str_starts("B.1.617") ~ "B.1.617",
  #   TRUE ~ type
  # )) %>% 
  group_by(type) %>% summarise(`vam latest` = max(earliest_specimen_date,na.rm = TRUE),`vam sequences` = n())

tmp1 %>% inner_join(tmp2, by="type") %>% saveTable(here::here("output/ClimbVsVAM"))


climbPheCounts = bind_rows(
  climb %>% filter(adm1=="UK-ENG" & sample_date >= "2021-02-01" & sample_date < "2021-04-01") %>% group_by(date = sample_date) %>% count() %>% mutate(source = "COGUK"),
  allVoc %>% filter(specimen_date >= "2021-02-01" & specimen_date < "2021-04-01") %>% group_by(date = specimen_date) %>% count() %>% mutate(source = "PHE")
)

tmp = climbPheCounts %>% pivot_wider(values_from = n,names_from=source) %>% mutate(diff = COGUK-PHE)

if ( sum(tmp$diff)/sum(tmp$COGUK) > 0.01 ) {
  stop("more than 1% difference in COG and PHE counts")
} else {
  message(sprintf("%1.3f%% mismatch between COG UK and PHE counts.",  sum(tmp$diff)/sum(tmp$COGUK)))
}



```

# Additional figures

```{r}
cog = dpc$datasets$getCOGUK()

xmap = cogUKMap %>% sf::st_centroid(cogUKMap) %>% dpc$geog$getContainedIn(outputMapId = "NHSER20",inputIdVar = iso_3166_2_code)
NHSERmap = dpc$geog$getMap("NHSER20")
cogNHSER = cog %>% inner_join(xmap,by=c("iso_3166_code"="from")) %>% rename(code=to) %>% dpc$codes$findNamesByCode()

window=14
cogMaxDate = max(cog$sample_date, na.rm = TRUE)

cogNHSER2 = cogNHSER %>% 
  mutate(topLineage = case_when(
    lineage %>% stringr::str_starts(fixed("B.1.177")) ~  "B.1.177",
    lineage %>% stringr::str_starts(fixed("B.1.1.7")) ~  "B.1.1.7",
    lineage %>% stringr::str_starts(fixed("P.1")) ~  "P.1 & P.2",
    lineage %>% stringr::str_starts(fixed("P.2")) ~  "P.1 & P.2",
    lineage %>% stringr::str_starts(fixed("B.1.351")) ~  "B.1.351",
    lineage %>% stringr::str_starts(fixed("B.1.525")) ~  "B.1.525",
    lineage %>% stringr::str_starts(fixed("B.1.1.318")) ~  "B.1.1.318",
    TRUE ~  "other")) %>%
  group_by(code,name, topLineage,sample_date) %>% 
  summarise(count = n()) %>%
  ungroup() %>% 
  tidyr::complete(nesting(code,name),sample_date,topLineage, fill=list(count=0)) %>%
  group_by(code,name,topLineage) %>% 
  arrange(sample_date) %>%
  mutate(Roll.count = stats::filter(count,filter=rep(1,window),sides=1)) %>%
  filter(!is.na(Roll.count))

cogNHSER3 = cogNHSER2 %>% 
  group_by(code,name,sample_date) %>% 
  mutate(binom::binom.confint(Roll.count, sum(Roll.count), conf.level = 0.95, methods = "wilson")) %>% 
  rename(Roll.mean = mean,Roll.lower = lower,Roll.upper=upper) %>%
  mutate(binom::binom.confint(count, sum(count), conf.level = 0.95, methods = "wilson")) %>% 
  select(-x,-n,-method) %>%
  mutate(topLineage = topLineage %>% forcats::as_factor() %>% forcats::fct_relevel("B.1.1.7"))

p1 = ggplot(cogNHSER3 %>% filter(sample_date>"2020-08-01" & sample_date<(cogMaxDate-14)),aes(x=sample_date,y=Roll.mean,fill=topLineage %>% forcats::fct_rev()))+geom_area()+
  facet_wrap(vars(name))+scale_fill_viridis_d(option = "viridis", name="lineage")+scale_x_date(date_breaks = "1 month", date_labels = "%m-%y")+geom_vline(xintercept = as.Date("2020-10-21"))

p1 %>% standardPrintOutput::saveThirdPageFigure(here::here("output/COGProportions-Now"))


```

```{r}

sGene = dpc$spim$getSDropoutFreqency(codeTypes = "NHSER",S_CT = 30,ORF1ab_CT = 30,N_CT = 30, equivocal.rm = TRUE) %>%
  mutate(sGene = sGene %>% forcats::as_factor() %>% forcats::fct_relevel("Negative"))

p1 = ggplot(sGene %>% filter(date>"2020-08-01" & date<(Sys.Date()) & sGene=="Negative"), aes(x=date,y=Roll.mean,ymin=Roll.lower,ymax=Roll.upper))+geom_ribbon(fill="blue",alpha=0.2)+geom_line(colour="blue")+facet_wrap(vars(name)) + 
  geom_vline(xintercept = as.Date("2020-10-21"))+scale_x_date(date_breaks = "1 month", date_labels = "%m-%y")

p1 %>% standardPrintOutput::saveThirdPageFigure(here::here("output/SgeneProportions-Now"))

```

# Airport data general population comparison

```{r}

tmp = dpc$demog$getDemographicsForCodeTypes(codeTypes = "CTRY",ageBreaks = c(2,11,16,20,25,35,45,55,60,65,75,85),combineGenders = TRUE)
tmp = tmp %>% group_by(code) %>% mutate(percentage = count/sum(count))
ggplot(tmp %>% filter(ageCat != "<2"),aes(x=ageCat,fill=code,y = percentage))+geom_bar(stat="identity",position = "dodge")
tmp %>% readr::write_csv(here::here("output/population-proportions-by-CAA-age-bands.csv"))
```
